### ISSUE TITLE
scsi_debug module is not available

### ISSUE THREAD

**Issue by gitPo1son** [osandov/blktests#101]
the scsi_debug module cannot be tested on the fedora,
the error message "scsi_debug module is not available" appears,
```
# ./check block
block/001 (stress device hotplugging)                        [not run]
    scsi_debug module is not available
block/002 (remove a device while running blktrace)           [not run]
    scsi_debug module is not available
```

it is caused by <https://github.com/osandov/blktests/blob/master/common/rc>   line 33 and 34,
```
_module_file_exists()
{
	local ko_underscore=${1//-/_}.ko
	local ko_hyphen=${1//_/-}.ko
```
on fedora, modules end with .ko.xz,I hope these two lines can be modified to be compatible with the module naming format of different platforms

Thanks,

**Comment by kawasaki** [comment]
@gitPo1son Thanks for the report. I will think about solution. ko.gz and ko.zst will need care also.

**Comment by kawasaki** [comment]
I posted [a fix patch](https://lore.kernel.org/linux-block/20220912054600.310858-1-shinichiro.kawasaki@wdc.com/) to linux-block list.

**Comment by gitPo1son** [comment]
@kawasaki   scsi_debug module works fine with your modification,thanks!

**Comment by kawasaki** [comment]
I have applied the fix patch. Close this issue.
