### ISSUE TITLE
Shellcheck will help to clean up your code...

### ISSUE THREAD

**Issue by TriMoon** [osandov/blktests#106]
See: https://github.com/koalaman/shellcheck/issues/2663

> Those about `$?` _(SC2320)_ are proof of bad coding, which **you should** correct...
> - https://github.com/osandov/blktests/blob/master/common/multipath-over-rdma#L134
>   Does this code have any chance of returning different return codes at all? :thinking: :rofl:
>   ```
>   [ -n "$1" ] || return $?
>   ```
> I'm sure the rest are similar... :rofl:

**Comment by kawasaki** [comment]
@TriMoon Thanks for the notice. I run shellcheck often for blktests and watches out to keep zero warning. But my Fedora system still has shellcheck version 0.8.0. It looks that version 0.9.0 reports more warnings. These warnings are being discussed in another pull request #107.

**Comment by kawasaki** [comment]
Recent changes in blktests addressed all of the warnings shellcheck version 0.9.0 reports. Thank goes to @bvanassche :)
