### ISSUE TITLE
loop0 loop1 loop2 still exists after loop/006

### ISSUE THREAD

**Issue by yizhanglinux** [osandov/blktests#126]
Hello
After loop/006, the `/dev/loop0 /dev/loop1 /dev/loop2` still exists and cannot be removed by `losetup -d`, but can be removed after the loop module remove, not sure if it's one tests issue or kernel issue?

```
# ./check loop/006
loop/006 (change loop backing file while creating/removing another loop device) [passed]
    runtime    ...  31.201s
# ll /dev/loop*
crw-rw----. 1 root disk 10, 237 Oct 17 08:02 /dev/loop-control
brw-rw----. 1 root disk  7,   0 Oct 17 08:03 /dev/loop0
brw-rw----. 1 root disk  7,   1 Oct 17 08:03 /dev/loop1
brw-rw----. 1 root disk  7,   2 Oct 17 08:03 /dev/loop2

# losetup -d /dev/loop0
losetup: /dev/loop0: detach failed: No such device or address

# losetup -d /dev/loop1
losetup: /dev/loop1: detach failed: No such device or address

# losetup -d /dev/loop2
losetup: /dev/loop2: detach failed: No such device or address

# rmmod loop

# ll /dev/loop*
crw-rw----. 1 root disk 10, 237 Oct 17 08:04 /dev/loop-control
```

**Comment by kawasaki** [comment]
Hi @yizhanglinux 

I confirmed that the /dev/loopX files exist after I ran any of loop/00X test case on my test systems.
 
I think it's ok that these files are left after the test. The files even exist just after loading the loop module, before setting up loop devices.
```
[root@testnode2 ~]# ls /dev/loop*
/dev/loop-control
[root@testnode2 ~]# modprobe loop
[root@testnode2 ~]# ls /dev/loop*
/dev/loop0  /dev/loop2  /dev/loop4  /dev/loop6  /dev/loop-control
/dev/loop1  /dev/loop3  /dev/loop5  /dev/loop7
```
The number of /dev/loopX files are defined in the kernel config as CONFIG_BLK_DEV_LOOP_MIN_COUNT. In my test system it has value 8, then eight /dev/loopX files are created. I read the loop driver code and found __init() function of the loop module creates the files, and removes in its __exit() function.

So it is current loop driver design to see the files before module unload. That should not harm following test runs.

**Comment by yizhanglinux** [comment]
> Hi @yizhanglinux
> 
> I confirmed that the /dev/loopX files exist after I ran any of loop/00X test case on my test systems.
> 
> I think it's ok that these files are left after the test. The files even exist just after loading the loop module, before setting up loop devices.
> 
> ```
> [root@testnode2 ~]# ls /dev/loop*
> /dev/loop-control
> [root@testnode2 ~]# modprobe loop
> [root@testnode2 ~]# ls /dev/loop*
> /dev/loop0  /dev/loop2  /dev/loop4  /dev/loop6  /dev/loop-control
> /dev/loop1  /dev/loop3  /dev/loop5  /dev/loop7
> ```
> 
> The number of /dev/loopX files are defined in the kernel config as CONFIG_BLK_DEV_LOOP_MIN_COUNT. In my test system it has value 8, then eight /dev/loopX files are created. I read the loop driver code and found __init() function of the loop module creates the files, and removes in its __exit() function.
> 
> So it is current loop driver design to see the files before module unload. That should not harm following test runs.

OK, thanks for looking it, close it now.
