### ISSUE TITLE
loop/009 fails with unrecognized option '--ping'

### ISSUE THREAD

**Issue by disgoel** [osandov/blktests#129]
The loop/009 test fails on older versions of systemd (prior to 241) because the new option --ping does not exist.

Reading through the announcement for systemd 241, we see mention of the new ping option there:
https://lists.freedesktop.org/archives/systemd-devel/2019-February/042169.html
 * udevadm control learnt a new option for --ping for testing whether a
          systemd-udevd instance is running and reacting

udevadm -V
239 (239-78.el8)

./check loop/009
loop/009 (check that LOOP_CONFIGURE sends uevents for partitions) [failed]
    runtime  0.460s  ...  0.481s
    --- tests/loop/009.out	2023-11-27 05:09:08.000000000 -0600
    +++ /root/blktests-master/results/nodev/loop/009.out.bad	2023-11-28 07:09:35.959089187 -0600
    @@ -1,3 +1,4 @@
     Running loop/009
    +control: unrecognized option '--ping'
     KERNEL add      /devices/virtual/block/loop_/loop_p1 (block)
     Test complete

udevadm control --ping
control: unrecognized option '--ping'

**Comment by kawasaki** [comment]
@disgoel Thanks for the report. It looks the test case relies on the --ping option. So I think the test case should be skipped with the older systemd. I created a commit which checks availability of the option, and skip if it's not available. 

https://github.com/kawasaki/blktests/commit/01700300e9e5ede478b7b4dc415421e3a1e1ea67

Could you try it and confirm that the test case is skipped in your environment?

**Comment by disgoel** [comment]
Thanks for the fix @kawasaki. I have tested on my environment and the test skips.

./check loop/009
loop/009 (check that LOOP_CONFIGURE sends uevents for partitions) [not run]
    runtime  0.481s  ...
    udevadm control does not support --ping option

**Comment by kawasaki** [comment]
Thanks for testing! I [posted the patch to linux-block list](https://lore.kernel.org/linux-block/20231129113616.663934-1-shinichiro.kawasaki@wdc.com/T/#u) for review.

**Comment by kawasaki** [comment]
Now the fix is applied.
https://github.com/osandov/blktests/commit/b5fad1ed3cbfbeb2f33e18ff208008bffb594c81
Let me close this case. Thanks!
