### ISSUE TITLE
blktests nbd/001 failed due to the output of 'lsblk -n /dev/nbd0'

### ISSUE THREAD

**Issue by yizhanglinux** [osandov/blktests#132]
# uname -r
6.8.0-rc3+
# lsblk --version
lsblk from util-linux 2.40-rc1

# ./check nbd/001
nbd/001 (resize a connected nbd device)                      [failed]
    runtime  0.027s  ...  0.423s
    --- tests/nbd/001.out	2024-02-18 06:47:36.303147966 -0500
    +++ /mnt/tests/gitlab.com/api/v4/projects/19168116/repository/archive.zip/storage/blktests/blk/blktests/results/nodev/nbd/001.out.bad	2024-02-18 11:20:58.775548133 -0500
    @@ -1,6 +1,6 @@
     Running nbd/001
     Disk /dev/nbd0: 10.7GB
    -nbd0  43:0    0  10G  0 disk
    +nbd0  43:0   0   10G 0 disk
     Setting size to 1gib
    -nbd0  43:0    0   1G  0 disk
    +nbd0  43:0   0    1G 0 disk
    ...
    (Run 'diff -u tests/nbd/001.out /mnt/tests/gitlab.com/api/v4/projects/19168116/repository/archive.zip/storage/blktests/blk/blktests/results/nodev/nbd/001.out.bad' to see the entire diff)

**Comment by yizhanglinux** [comment]
@karelzak do you know if `lsblk -n` output changed recently?

**Comment by karelzak** [comment]
> @karelzak do you know if `lsblk -n` output changed recently?

It appears that the differences are primarily related to formatting, correct? However, there are substantial changes in libsmartcols, which lsblk relies on for generating output.

If your focus is solely on data integrity in your tests, utilizing the `lsblk --raw` output option might be advisable. This would enhance the robustness of your tests.

**Comment by yizhanglinux** [comment]
> > @karelzak do you know if `lsblk -n` output changed recently?
> 
> It appears that the differences are primarily related to formatting, correct? However, there are substantial changes in libsmartcols, which lsblk relies on for generating output.
> 

Yes, will update to use the raw mode, thanks for the info.

> If your focus is solely on data integrity in your tests, utilizing the `lsblk --raw` output option might be advisable. This would enhance the robustness of your tests.
