### ISSUE TITLE
Random nbd/001 failure

### ISSUE THREAD

**Issue by yizhanglinux** [osandov/blktests#141]
CKI reported nbd/001 failure[2] last week on[1], I added the full log as [3], please help check it, thanks. 

[1]
Commit message: Merge tag 'block-6.10-20240614' of git://[git.kernel.dk/linux](http://git.kernel.dk/linux)
[2]
----------------------34
nbd/001 (resize a connected nbd device)                      [failed]
    runtime  1.380s  ...  3.093s
    --- tests/nbd/001.out	2024-06-16 23:20:50.138357965 -0400
    +++ /root/blktests_up/results/nodev/nbd/001.out.bad	2024-06-16 23:26:55.546888054 -0400
    @@ -1,6 +1,4 @@
     Running nbd/001
    -Disk /dev/nbd0: 10.7GB
    -nbd0 43:0 0 10G 0 disk
    +nbd0 43:0 0 0B 0 disk
     Setting size to 1gib
    -nbd0 43:0 0 1G 0 disk
    -Disk /dev/nbd0: 1074MB
    ...
    (Run 'diff -u tests/nbd/001.out /root/blktests_up/results/nodev/nbd/001.out.bad' to see the entire diff)
[3]
[root@storageqe-05 blktests_up]# dmesg | tail -1
[ 2198.516581] run blktests nbd/001 at 2024-06-16 23:26:52

[root@storageqe-05 blktests_up]# cat results/nodev/nbd/001.out.bad
Running nbd/001
nbd0 43:0 0 0B 0 disk
Setting size to 1gib
nbd0 43:0 0 0B 0 disk
[root@storageqe-05 blktests_up]# cat results/nodev/nbd/001.full
Error: Socket failed: Connection refused

**Comment by kawasaki** [comment]
I think this failure has same root case as #142, and the fix 0c3dfdda8c58 for #142 is now in the master branch. Let me close this case.
