### ISSUE TITLE
loop/010 test fails on power

### ISSUE THREAD

**Issue by disgoel** [osandov/blktests#143]
The loop/010 test fails on power with below error.
```
# ./check loop/010
loop/010 (check stale loop partition)                        [failed]
    runtime  91.245s  ...  91.295s
    --- tests/loop/010.out	2024-07-10 01:37:15.553113263 -0500
    +++ /home/disha/blktests/results/nodev/loop/010.out.bad	2024-07-10 02:13:10.802682524 -0500
    @@ -1,2 +1,3 @@
     Running loop/010
    +Fail
     Test complete

# cat /home/disha/blktests/results/nodev/loop/010.out.bad
Running loop/010
Fail
Test complete

# uname -r
6.10.0-rc7-00012-g34afb82a3c67
```

**Comment by kawasaki** [comment]
@disgoel Thanks for the care for this failure.
CC: @gulams 

My understanding is that the kernel side fix is available, and it is queued for the kernel v6.11.

References:

- https://lore.kernel.org/linux-block/20240618164042.343777-1-gulam.mohamed@oracle.com/
- https://git.kernel.org/pub/scm/linux/kernel/git/axboe/linux-block.git/commit/?h=for-6.11/block&id=18048c1af7836b8e31739d9eaefebc2bf76261f7

I'm not sure if the fix in kernel will be ported to the stable kernels older than v6.11. If that won't happen, the test case may need modification to skip for the older kernels.

**Comment by disgoel** [comment]
Thanks @kawasaki

With the changes applied, loop/010 test passed. Maybe we should modify the test case for older kernels since 6.11 is very far from distro supported kernel.
```
# ./check loop/010
loop/010 (check stale loop partition)                        [passed]
    runtime  91.295s  ...  91.132s
```

**Comment by PraveenPenguin** [comment]
@kawasaki @disgoel This PR can skip this test in the old kernel till that time kernel patches are not backported , please review and let me know if this looks ok 

https://github.com/osandov/blktests/pull/144

**Comment by kawasaki** [comment]
@PraveenPenguin Thanks. I took another look in the kernel side fix, and I do not see either CC:stable or Fixes tag, so I assume the fix will not be ported to stable kernels. With a quick glance, the PR looks good. I will do the final check of the PR tomorrow.

**Comment by disgoel** [comment]
Thanks for the fix @PraveenPenguin. This looks good.

**Comment by kawasaki** [comment]
I have applied the fix by @PraveenPenguin with some manual edits. @disgoel Could you confirm the fix?

**Comment by disgoel** [comment]
> I have applied the fix by @PraveenPenguin with some manual edits. @disgoel Could you confirm the fix?

Fix works fine. Closing the issue as fixed.
