### ISSUE TITLE
Support setting config options as environment variables

### ISSUE THREAD

**Issue by mrnuke** [osandov/blktests#25]
Running check with -d option doesn't work for me. I would have expected that -d takes a list of devices rather than reading some environment variable. Hoewever, even setting TEST_DEVS doesn't seem to work:

	[root@g-prime blktests]# TEST_DEVS=/dev/nvme0n1 ./check -d
	./check: DEVICE_ONLY specified without TEST_DEVS

Or:

	[root@g-prime blktests]# TEST_DEVS=(/dev/nvme0n1) ./check -d
	./check: DEVICE_ONLY specified without TEST_DEVS

Or:

	[root@g-prime blktests]# sh
	sh-4.4# TEST_DEVS=(/dev/nvme0n1 /dev/sdb)
	sh-4.4# ./check -d
	./check: DEVICE_ONLY specified without TEST_DEVS
	sh-4.4# TEST_DEVS=(/dev/nvme0n1 /dev/sdb) ./check -d
	./check: DEVICE_ONLY specified without TEST_DEVS

**Comment by osandov** [comment]
@mrnuke as per the README, you have to define the list of block devices to use in a file named `config` at the top level of the blktests repo. It seems reasonable that you'd want to pass it on the command line, though, I can add support for that.

**Comment by mrnuke** [comment]
Okay, I missed the putting it all in a file named 'config'. I guess I wasn't expecting that. I think the command line would be a great way to specify options.
