### ISSUE TITLE
Some tests fail with "'device' is not a PCI device"

### ISSUE THREAD

**Issue by mrnuke** [osandov/blktests#26]
I was trying to run the batch of tests, and noticed that some tests fail with `device is not a PCI device':

	[root@g-prime blktests]# cat config 
	TEST_DEVS=(/dev/nvme2n1)
	[root@g-prime blktests]# ./check  -d
	cat: /sys/block/nvme2c33n1/dev: No such file or directory
	[snip]
	block/011 => nvme2n1 (disable PCI device while doing I/O)    [not run]
	    /dev/nvme2n1 is not a PCI device

Looking a bit, I tried to find the logic that decides whether the device is a PCI device or not:

	[root@g-prime blktests]# source check
	^C
	[root@g-prime blktests]# readlink -f $(_find_sysfs_dir /dev/nvme2n1)
	cat: /sys/block/nvme2c33n1/dev: No such file or directory
	/sys/devices/virtual/nvme-subsystem/nvme-subsys2/nvme2n1
	[root@g-prime blktests]# readlink -f $(_find_sysfs_dir /dev/nvme2)
	/sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:04.0/0000:b1:00.0/nvme/nvme2/nvme1n1

Okay, the `/dev/nvme2` node eventually traces back to a PCI device. Maybe I need to use this one, but this is also not accepted by the framework:

	[root@g-prime blktests]# cat config 
	TEST_DEVS=(/dev/nvme2)
	[root@g-prime blktests]# ./check  -d
	./check: /dev/nvme2 is not a block device

I suspect I'm either using this completely wrong, or something else is broken along the way.

**Comment by osandov** [comment]
@morbidrsa can you please take a look.

**Comment by morbidrsa** [comment]
@mrnuke can you give me the output of  ```tree /sys/devices/virtual/nvme-subsystem/nvme-subsys2/nvme2n1```

**Comment by mrnuke** [comment]
```
#  tree /sys/devices/virtual/nvme-subsystem/nvme-subsys2/nvme2n1
/sys/devices/virtual/nvme-subsystem/nvme-subsys2/nvme2n1
├── alignment_offset
├── bdi -> ../../../bdi/259:5
├── capability
├── dev
├── device -> ../../nvme-subsys2
├── discard_alignment
├── eui
├── ext_range
├── hidden
├── holders
├── inflight
├── integrity
│   ├── device_is_integrity_capable
│   ├── format
│   ├── protection_interval_bytes
│   ├── read_verify
│   ├── tag_size
│   └── write_generate
├── nguid
├── nsid
├── power
│   ├── autosuspend_delay_ms
│   ├── control
│   ├── runtime_active_time
│   ├── runtime_status
│   └── runtime_suspended_time
├── queue
│   ├── add_random
│   ├── chunk_sectors
│   ├── dax
│   ├── discard_granularity
│   ├── discard_max_bytes
│   ├── discard_max_hw_bytes
│   ├── discard_zeroes_data
│   ├── fua
│   ├── hw_sector_size
│   ├── io_poll
│   ├── io_poll_delay
│   ├── iostats
│   ├── logical_block_size
│   ├── max_discard_segments
│   ├── max_hw_sectors_kb
│   ├── max_integrity_segments
│   ├── max_sectors_kb
│   ├── max_segments
│   ├── max_segment_size
│   ├── minimum_io_size
│   ├── nomerges
│   ├── nr_requests
│   ├── optimal_io_size
│   ├── physical_block_size
│   ├── read_ahead_kb
│   ├── rotational
│   ├── rq_affinity
│   ├── scheduler
│   ├── wbt_lat_usec
│   ├── write_cache
│   ├── write_same_max_bytes
│   ├── write_zeroes_max_bytes
│   └── zoned
├── range
├── removable
├── ro
├── size
├── slaves
├── stat
├── subsystem -> ../../../../../class/block
├── trace
│   ├── act_mask
│   ├── enable
│   ├── end_lba
│   ├── pid
│   └── start_lba
├── uevent
├── uuid
└── wwid

9 directories, 67 files
```

**Comment by morbidrsa** [comment]
@mrnuke can you try the branch I've pushed to https://github.com/morbidrsa/blktests/tree/issue26 ?

**Comment by mrnuke** [comment]
@morbidrsa Sweet! I can run the tests with /dev/nvmexnx  as TEST_DEVS.

Thanks you for looking into this!

**Comment by morbidrsa** [comment]
@mrnuke thanks for the confirming the fix. Send out pull request to @osandov
