### ISSUE TITLE
Failed case exit with 0 which introduced from e840e1537dc62dabfe9d59e5288b9318a2d7c50b

### ISSUE THREAD

**Issue by yide1728** [osandov/blktests#46]
[root@storageqe-72 blktests]# git checkout e840e1537dc62dabfe9d59e5288b9318a2d7c50b
[root@storageqe-72 blktests]# ./check block/024
block/024 (do I/O faster than a jiffy and check iostats times) [failed]
    runtime  2.514s  ...  2.519s
    --- tests/block/024.out	2019-02-15 07:25:04.391922614 +0100
    +++ /mnt/tests/distribution/command/blktests/results/nodev/block/024.out.bad	2019-02-15 07:48:07.190199759 +0100
    @@ -6,5 +6,5 @@
     read 1 s
     write 1 s
     read 2 s
    -write 3 s
    +write 2 s
     Test complete
[root@storageqe-72 blktests]# echo $?
0
[root@storageqe-72 blktests]# git reset --hard HEAD~1
HEAD is now at a58b974 loop: Add test for changing capacity when filesystem is mounted
[root@storageqe-72 blktests]# ./check block/024
block/024 (do I/O faster than a jiffy and check iostats times) [failed]
    runtime  2.519s  ...  2.509s
    --- tests/block/024.out	2019-02-15 07:25:04.391922614 +0100
    +++ /mnt/tests/distribution/command/blktests/results/nodev/block/024.out.bad	2019-02-15 07:48:31.308880877 +0100
    @@ -6,5 +6,5 @@
     read 1 s
     write 1 s
     read 2 s
    -write 3 s
    +write 2 s
     Test complete
[root@storageqe-72 blktests]# echo $?
1

**Comment by osandov** [comment]
Fixed by 73c2eb3ac6f1 ("Fix the failure case which will exit with 0").
