### ISSUE TITLE
function _get_pci_dev_from_blkdev doesn't work

### ISSUE THREAD

**Issue by yide1728** [osandov/blktests#5]
Hi
On latest 4.14.0-rc5, the _get_pci_dev_from_blkdev function can get 4 pdev, which lead block/011 failed. Could we add "tail -1" at the end to fix it?
[1]
# uname -r
4.14.0-rc5.EDAC+
# lspci | grep -i non
84:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172X (rev 01)

[2]
# readlink -f /sys/block/nvme0n1/device | grep -Eo '[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]'
0000:80:02.0
0000:82:00.0
0000:83:04.0
0000:84:00.0

Thanks
Yi

**Comment by osandov** [comment]
Thanks for the report, should be fixed.
