### ISSUE TITLE
block/007, Android doesn't support pvsync2

### ISSUE THREAD

**Issue by ChanChunSong** [osandov/blktests#65]
Hi,
Because Android doesn't support pvsync2. Can this test case use another IO engine?
I'm not sure the purpose of the test case. Could you give me some suggestion ?

**Comment by osandov** [comment]
block/007 tests I/O polling, which is only available via pvsync2 (using the `preadv2`/`pwritev2` syscalls). We either need a helper which tests whether the kernel supports `preadv2` and `pwritev2`.

**Comment by OceanOhen** [comment]
How to test kernel supports these two functions?

**Comment by osandov** [comment]
Probably a small program in `src/` that calls `preadv2()` and `pwritev2()` and returns whether it failed with `ENOSYS` (unless fio provides an easy way to detect it).
