### ISSUE TITLE
block/009 verify cache dropped

### ISSUE THREAD

**Issue by ChanChunSong** [osandov/blktests#70]
Hi,

In this case, there're two xfs_io write command and two hexdump.
Why don't we only use one time xfs_io and hexdump ?

**Comment by osandov** [comment]
The first xfs_io pwrite is called with the -w flag, which flushes the data to disk. This initializes the disk to a known state. The second xfs_io pwrite does not have the -w flag, so the data likely is not written to disk yet. This populates the page cache with some testing data.

The first dd/hexdump does not have the direct flag set, so it reads from the page cache. This verifies that the page cache was properly invalidated. The second dd/hexdump uses the direct flag, so it verifies that the disk was discarded.

Hopefully this helps!
