### ISSUE TITLE
what's the fail case of block/016

### ISSUE THREAD

**Issue by ChanChunSong** [osandov/blktests#76]
I see the git log shows it's a regression test. If I commit a wrong patch causing the regression fail.
What's the fail symptom or log ?
I found the script only check the output message and exit value.

**Comment by osandov** [comment]
The original bug was that the kernel would return an I/O error if a signal was received while waiting for I/O at a certain point. In that case, the dd process will output an I/O error message, causing an output mismatch failure.

**Comment by ChanChunSong** [comment]
got it, thanks
