### ISSUE TITLE
block/018 question

### ISSUE THREAD

**Issue by ChanChunSong** [osandov/blktests#78]
The block/018 use the same read command twice again.
	dd if=/dev/nullb0 of=/dev/null bs=4096 iflag=direct count=1 status=none &
	dd if=/dev/zero of=/dev/nullb0 bs=4096 oflag=direct count=1 status=none &
	dd if=/dev/zero of=/dev/nullb0 bs=4096 oflag=direct count=1 status=none &
Is it for any special purpose ?

**Comment by osandov** [comment]
Yes, this does two writes to nullb0 in parallel to test that iostat counts both requests individually.
